name: Releases
on:
  push:
    branches: ["master"]

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release
          jq -r .version ./package.json

  print-verison:
    name: Print version
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - run: |
          echo ""
          echo "##############################"
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo ${tag:1}
          echo "##############################"
          echo ""
